#! /bin/sh
#!/bin/bash

# Set desktops after profile switch
if xrandr | grep "DP-0 connected"; then
    bspc monitor DP-0 -d 1 2 3 4 5
else
    bspc monitor -d 1 2 3 4 5
fi


bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config border_color "#4c566a"

bspc config focused_border_color "#3c3836"
bspc config normal_border_color "#1d2021"

~/.config/polybar/launch.sh &
