set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g mode-keys vi

set -g status-right ''
set -g status-right-length 0

# Status bar basics
set -g status on
set -g status-interval 1
set -g status-justify left
set -g status-style "bg=#1a1b26,fg=#c0caf5"

# Left side (session name)
set -g status-left-length 50
set -g status-left "#[fg=#7aa2f7,bg=#1a1b26,bold]  #S "

# Window styling
set -g window-status-format "#[fg=#565f89] #I:#W "

# Pane border
set -g pane-border-style "fg=#565f89"
set -g pane-active-border-style "fg=#7aa2f7"

# Current window
set -g window-status-current-format "#[bg=#7aa2f7,fg=#1a1b26,bold] #I #W #[bg=#1a1b26,fg=#7aa2f7]"
